import WorkspaceModuleClient from '@/components/WorkspaceModuleClient';

const modules: Record<string, { label: string; eyebrow: string; description: string; details: string[]; actions: { label: string; href: string }[] }> = {
  memory: { label: 'Memory', eyebrow: 'Context control', description: 'Review and curate the context Simha can reuse across your workspace.', details: ['Conversation-scoped memory is active.', 'Saved preferences and project context are isolated to your account.', 'Every memory change is auditable and reversible.'], actions: [{ label: 'Open memory in Workbench', href: 'https://chat.simhaonline.ai/chat' }, { label: 'Review routing data', href: 'https://platform.simhaonline.ai/' }] },
  skills: { label: 'Skill Modules', eyebrow: 'Reusable capabilities', description: 'Manage capabilities, permissions, and connection requirements from one place.', details: ['Skills declare permissions before activation.', 'Connector dependencies are checked before execution.', 'Execution history is recorded in workspace telemetry.'], actions: [{ label: 'Browse Asset Library', href: 'https://chat.simhaonline.ai/workspace/library' }, { label: 'Configure connectors', href: 'https://platform.simhaonline.ai/' }] },
  agents: { label: 'Agent Profiles', eyebrow: 'Orchestration', description: 'Configure focused roles for research, coding, analysis, and operations.', details: ['Profiles can be connected to routed models.', 'Tool access and permissions are explicit per profile.', 'Multi-step execution surfaces progress, retries, and failures.'], actions: [{ label: 'Start an agent chat', href: 'https://chat.simhaonline.ai/chat' }, { label: 'Manage models', href: 'https://platform.simhaonline.ai/' }] },
  code: { label: 'Code Studio', eyebrow: 'Developer workspace', description: 'A focused space for code generation, review, and reusable snippets.', details: ['Code requests use the capability-aware router.', 'Generated snippets can be saved to the Asset Library.', 'Execution requires an explicitly configured tool connector.'], actions: [{ label: 'Open Workbench', href: 'https://chat.simhaonline.ai/chat' }, { label: 'Open connector settings', href: 'https://platform.simhaonline.ai/' }] },
  mcp: { label: 'MCP Connectors', eyebrow: 'Tool connectivity', description: 'Connect tools and resources through a permissioned integration boundary.', details: ['Connected servers show health, latency, and permissions.', 'Tool calls require an enabled connector and user consent.', 'Connector activity is recorded for auditability.'], actions: [{ label: 'Open Control Center', href: 'https://platform.simhaonline.ai/' }, { label: 'Read integration docs', href: 'https://docs.simhaonline.ai/' }] },
  plugins: { label: 'Plugin Gallery', eyebrow: 'Extensions', description: 'Discover and manage extensions for the Simha workspace.', details: ['Installed extensions are isolated from provider credentials.', 'Plugin permissions are reviewed before activation.', 'Every enable, disable, install, and update is audited.'], actions: [{ label: 'Open Asset Library', href: 'https://chat.simhaonline.ai/workspace/library' }, { label: 'Manage integrations', href: 'https://platform.simhaonline.ai/' }] },
  data: { label: 'Data Explorer', eyebrow: 'Files and datasets', description: 'Find reusable datasets and ingestion results from your private workspace.', details: ['Uploaded files are stored in your private object-storage namespace.', 'Parsed text and chunks are searchable when processing completes.', 'Dataset connectors report their source, status, and last sync.'], actions: [{ label: 'Open Workbench intake', href: 'https://chat.simhaonline.ai/chat' }, { label: 'View ingestion status', href: 'https://platform.simhaonline.ai/' }] },
};

export default async function WorkspaceModulePage({ params }: { params: Promise<{ module: string }> }) {
  const module = modules[(await params).module] || modules.skills;
  return <WorkspaceModuleClient module={module} />;
}
