'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import TopBar from '@/components/TopBar';

const slides = [
  { eyebrow: 'One intelligent edge', title: 'Every model. One calm, reliable API.', body: 'Simha routes production AI traffic across OpenAI, Anthropic, Gemini, and self-hosted models with the controls your team needs to ship confidently.', visual: 'routing' },
  { eyebrow: 'Built for production teams', title: 'Make AI infrastructure feel simple.', body: 'Keep provider credentials server-side, enforce budgets before dispatch, and let intelligent failover protect your uptime and your spend.', visual: 'control' },
  { eyebrow: 'OpenAI-compatible by design', title: 'Bring your SDKs. Keep your momentum.', body: 'Point the tools you already use at one OpenAI-compatible endpoint and unlock a unified model catalog, usage history, and client-key controls.', visual: 'developer' },
];

const features = [
  ['01', 'Multi-provider routing', 'Pool OpenAI, Anthropic, Gemini, and Ollama accounts behind one stable endpoint.'],
  ['02', 'Automatic failover', 'Cooldowns, strikes, capacity windows, and model-aware retries keep requests moving.'],
  ['03', 'Budget guardrails', 'Apply rolling minute, day, and week limits before a request reaches a provider.'],
  ['04', 'Semantic caching', 'Reuse safe, relevant responses with pgvector-backed prompt similarity.'],
  ['05', 'Usage intelligence', 'See request history, token usage, account health, and client activity in one place.'],
  ['06', 'Secure credentials', 'Provider secrets stay server-side while client keys are hashed and scoped.'],
  ['07', 'Workbench included', 'Chat, projects, saved prompts, scheduled work, and image generation in the same account.'],
  ['08', 'OpenAI-compatible', 'Use familiar SDKs, streaming SSE, /v1/models, and /v1/chat/completions.'],
];

function Arrow() { return <span aria-hidden="true">↗</span>; }

function ProductVisual({ type }: { type: string }) {
  if (type === 'developer') {
    return <div className="hero-code-window"><div className="window-bar"><span /><span /><span /><b>quickstart.py</b></div><pre>{['from openai import OpenAI', '', 'client = OpenAI(', '  base_url="https://api.simhaonline.ai/v1",', '  api_key="sek_..."', ')', '', 'response = client.chat.completions.create(', '  model="claude-sonnet-4",', '  messages=[{"role": "user", "content": prompt}]', ')'].join('\n')}</pre><div className="code-status"><i /> Connected to Simha Edge <span>200 OK</span></div></div>;
  }
  return <div className={`hero-console ${type}`}><div className="console-top"><span className="console-brand"><i /> SIMHA / EDGE ROUTER</span><span className="console-live"><i /> ALL SYSTEMS OPERATIONAL</span></div><div className="console-body"><aside><div className="rail-line wide" /><div className="rail-line" /><div className="rail-line active" /><div className="rail-line" /><div className="rail-line short" /><div className="rail-sep" /><div className="rail-line" /><div className="rail-line short" /></aside><div className="console-main">{type === 'routing' ? <><div className="console-heading"><div><small>ROUTING OVERVIEW</small><strong>Traffic, intelligently placed.</strong></div><em>LIVE</em></div><div className="route-map"><div className="route-node source">REQUEST<div>gpt-4o</div></div><div className="route-lines"><span /><span /><span /></div><div className="route-nodes"><div><i className="green" /> OpenAI <b>42ms</b></div><div><i className="blue" /> Anthropic <b>68ms</b></div><div><i className="amber" /> Ollama <b>local</b></div></div></div><div className="metric-row"><div><small>REQUESTS / MIN</small><b>1,284</b><span>+18.4%</span></div><div><small>ACTIVE MODELS</small><b>24</b><span>across 6 providers</span></div><div><small>FAILOVER RATE</small><b>0.08%</b><span>last 24 hours</span></div></div></> : <><div className="console-heading"><div><small>POLICY ENGINE</small><strong>Guardrails that stay out of the way.</strong></div><em>ENFORCED</em></div><div className="activity-panel"><div className="activity-head"><span>POST /v1/chat/completions</span><b>● 200</b></div><div className="activity-grid"><div><small>MODEL</small><strong>claude-sonnet-4</strong></div><div><small>LATENCY</small><strong>812ms</strong></div><div><small>TOKENS</small><strong>2,481</strong></div></div><div className="activity-bar"><span style={{ width: '68%' }} /></div><div className="activity-foot"><span>budget / request</span><b>$0.05 cap</b></div></div><div className="console-log"><span>12:04:31</span> request accepted <i /> <span>12:04:32</span> policy checked <i /> <span>12:04:32</span> response streamed</div></>}</div></div></div>;
}

export default function HomeMarketing() {
  const [active, setActive] = useState(0);
  const [paused, setPaused] = useState(false);
  const slide = slides[active];
  useEffect(() => { if (paused) return; const timer = window.setInterval(() => setActive((current) => (current + 1) % slides.length), 6500); return () => window.clearInterval(timer); }, [paused]);

  return <div className="marketing-page">
    <TopBar />
    <main>
      <section className="marketing-hero" onMouseEnter={() => setPaused(true)} onMouseLeave={() => setPaused(false)}>
        <div className="hero-gridlines" />
        <div className="container marketing-hero-inner"><div className="hero-copy"><div className="hero-eyebrow"><i /> {slide.eyebrow}</div><h1>{slide.title}</h1><p>{slide.body}</p><div className="hero-actions"><Link href="/signup" className="marketing-btn primary">Start building <Arrow /></Link><Link href="/docs" className="marketing-btn secondary">Explore the docs</Link></div><div className="hero-proof"><span><i /> No provider keys in the browser</span><span>OpenAI-compatible</span><span>Built for teams</span></div></div><div className="hero-visual"><ProductVisual type={slide.visual} /></div></div>
        <div className="container hero-controls"><div className="slide-count"><b>0{active + 1}</b><span>/ 0{slides.length}</span></div><div className="slide-dots">{slides.map((item, index) => <button key={item.title} aria-label={`Show slide ${index + 1}`} className={active === index ? 'active' : ''} onClick={() => setActive(index)}><span /></button>)}</div><div className="slide-arrows"><button aria-label="Previous slide" onClick={() => setActive((active + slides.length - 1) % slides.length)}>←</button><button aria-label="Next slide" onClick={() => setActive((active + 1) % slides.length)}>→</button></div></div>
      </section>
      <section className="trust-strip"><div className="container trust-inner"><span>ONE LAYER BETWEEN YOUR APP AND THE MODEL</span><div><b>OPENAI SDK</b><b>ANTHROPIC</b><b>GEMINI</b><b>OLLAMA</b><b>POSTGRES</b></div></div></section>
      <section className="marketing-section intro-section"><div className="container split-heading"><div><div className="section-label">THE ROUTER LAYER</div><h2>AI infrastructure, without the operational sprawl.</h2></div><p>Simha gives your team a single place to connect providers, shape traffic, protect budgets, and understand what your applications are doing.</p></div></section>
      <section id="features" className="marketing-section feature-section"><div className="container"><div className="section-label">CAPABILITIES / 08</div><div className="feature-grid">{features.map(([number, title, copy]) => <article key={number} className="feature-item"><span className="feature-number">{number}</span><div><h3>{title}</h3><p>{copy}</p><Link href="/docs" aria-label={`Learn more about ${title}`}>Learn more <Arrow /></Link></div></article>)}</div></div></section>
      <section className="marketing-section architecture-section"><div className="container architecture-layout"><div className="architecture-copy"><div className="section-label">HOW IT WORKS</div><h2>A better path from prompt to production.</h2><p>Keep the application layer familiar while Simha handles the complexity underneath. Every request gets a consistent interface, an accountable route, and a useful paper trail.</p><div className="steps"><div><b>01</b><span><strong>Connect</strong><small>Add provider accounts once. Credentials remain protected on the server.</small></span></div><div><b>02</b><span><strong>Configure</strong><small>Set model policies, client keys, limits, and fallback preferences.</small></span></div><div><b>03</b><span><strong>Operate</strong><small>Monitor health and usage from one focused operator workbench.</small></span></div></div></div><div className="architecture-card"><div className="architecture-card-head"><span>REQUEST LIFECYCLE</span><i>REAL-TIME</i></div><div className="flow"><div className="flow-box">YOUR APP<small>OpenAI SDK</small></div><span className="flow-line" /><div className="flow-box accent-box">SIMHA EDGE<small>Route · Limit · Observe</small></div><span className="flow-line" /><div className="provider-stack"><div>OPENAI <i /></div><div>ANTHROPIC <i /></div><div>OLLAMA <i /></div></div></div><div className="architecture-card-foot"><span>SECURE BY DEFAULT</span><b>credentials never leave the edge</b></div></div></div></section>
      <section className="marketing-section api-section"><div className="container api-layout"><div><div className="section-label">DEVELOPER EXPERIENCE</div><h2>One endpoint. No migration project.</h2><p>Use the OpenAI client you already know. Change the base URL, add a Simha key, and keep building.</p><Link href="/docs" className="text-link">Read the integration guide <Arrow /></Link></div><div className="api-snippet"><div className="snippet-top"><span><i /> <i /> <i /></span><b>python</b><button>Copy</button></div><pre>{['from openai import OpenAI', '', 'client = OpenAI(', '    base_url="https://api.simhaonline.ai/v1",', '    api_key="sek_...",', ')', '', 'answer = client.chat.completions.create(', '    model="gpt-4o",', '    messages=messages,', ')'].join('\n')}</pre><div className="snippet-bottom"><span>Compatible with your existing stack</span><span>→ /v1/chat/completions</span></div></div></div></section>
      <section className="marketing-cta"><div className="container cta-inner"><div className="section-label">READY WHEN YOU ARE</div><h2>Make your next AI feature<br /><em>easier to operate.</em></h2><p>Start with the free plan. Bring your models, your SDKs, and your ambition.</p><div className="hero-actions"><Link href="/signup" className="marketing-btn primary">Create your account <Arrow /></Link><Link href="/pricing" className="marketing-btn secondary">View pricing</Link></div></div></section>
    </main>
    <footer className="marketing-footer"><div className="container footer-main"><div className="footer-brand"><Link href="/" className="footer-logo"><span>⌁</span> Simha Online</Link><p>One intelligent edge for every model you run.</p><div className="footer-status"><i /> All systems operational</div></div><div className="footer-links"><div><b>Product</b><Link href="#features">Features</Link><Link href="/chat">Workbench</Link><Link href="/pricing">Pricing</Link><Link href="/status">Status</Link></div><div><b>Developers</b><Link href="/docs">Documentation</Link><Link href="/docs">API reference</Link><Link href="/dashboard">Dashboard</Link><Link href="/signup">Get started</Link></div><div><b>Company</b><Link href="mailto:hello@simhaonline.ai">Contact</Link><Link href="/status">System status</Link></div></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} Simha Online. All rights reserved.</span><span>Built for reliable AI infrastructure.</span><span><Link href="/docs">Terms</Link><Link href="/docs">Privacy</Link></span></div></footer>
  </div>;
}
