'use client';

import Link from 'next/link';
import { useState } from 'react';
import TopBar from './TopBar';

type Module = { label: string; eyebrow: string; description: string; details: string[]; actions: { label: string; href: string }[] };

export default function WorkspaceModuleClient({ module }: { module: Module }) {
  const [activeTab, setActiveTab] = useState('Overview');
  return <><TopBar /><main className="workspace-module-page"><div className="workspace-module-inner"><div className="module-breadcrumb"><Link href="https://chat.simhaonline.ai/chat">Workbench</Link><span>/</span><span>{module.label}</span></div><div className="module-hero"><div><div className="module-kicker">{module.eyebrow}</div><h1>{module.label}</h1><p>{module.description}</p></div><span className="module-live"><i />Operational</span></div><div className="module-tabs" role="tablist">{['Overview', 'Activity', 'Settings'].map((tab) => <button key={tab} className={activeTab === tab ? 'active' : ''} onClick={() => setActiveTab(tab)}>{tab}</button>)}</div><section className="module-layout"><div className="module-card"><div className="module-card-head"><div><span className="module-card-kicker">Workspace status</span><h2>{activeTab === 'Overview' ? 'Ready for production use' : `${activeTab} controls`}</h2></div><span className="module-status"><i />Healthy</span></div><div className="module-card-body">{activeTab === 'Overview' ? <>{module.details.map((detail) => <div className="module-detail" key={detail}><b>✓</b><span>{detail}</span></div>)}<div className="module-actions">{module.actions.map((action, index) => <Link className={`btn ${index === 0 ? 'primary' : ''}`} href={action.href} key={action.href}>{action.label}</Link>)}</div></> : <div className="module-empty"><span>⌁</span><h3>{activeTab} is connected to this workspace</h3><p>Use the Control Center to manage permissions, telemetry, and persisted configuration.</p><Link className="btn primary" href="https://platform.simhaonline.ai/">Open Control Center</Link></div>}</div></div><aside className="module-side"><div className="module-side-card"><span className="module-card-kicker">Quick links</span><Link href="https://chat.simhaonline.ai/chat">← Return to Workbench</Link><Link href="https://platform.simhaonline.ai/">Control Center</Link><Link href="https://docs.simhaonline.ai/">Documentation</Link></div><div className="module-side-card"><span className="module-card-kicker">Protection</span><p>Workspace credentials remain server-side. Actions are authenticated, scoped, and recorded.</p></div></aside></section></div></main></>;
}
